# Generated by Django 3.2.8 on 2021-10-17 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('z_gram', '0004_follow'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='UserComment',
        ),
    ]
