# Generated by Django 3.2.8 on 2021-10-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_gram', '0005_rename_comment_usercomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='images/profile/user.png', upload_to='images/profile/'),
        ),
    ]
