# Generated by Django 3.2.8 on 2021-10-19 16:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('z_gram', '0007_auto_20211019_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dd5ab8mp3/image/upload/v1634659738/images/profile/user.jpg', max_length=255, verbose_name='image'),
        ),
    ]
